name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r $GITHUB_WORKSPACE/dev-requirements.txt
      - name: Check syntax
        run: |
          isort --diff --check ckanext/
          black --diff --check ckanext/
          flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
